packages:
  - 'apps/'
  - 'packages/'
  - 'apps/*'
  - 'libs/platform/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  detox: true
  dtrace-provider: true
  less: false
  nx: true
  sharp: true
  unrs-resolver: true
