GRANT CONNECT ON DATABASE ${DB_NAME} TO ${ADMIN_ROLE};

GRANT USAGE, CREATE ON SCHEMA ${SCHEMA_NAME} TO ${ADMIN_ROLE};

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA ${SCHEMA_NAME}
TO ${ADMIN_ROLE};

GRANT ALL PRIVILEGES
ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME}
TO ${ADMIN_ROLE};

GRANT ALL PRIVILEGES
ON ALL FUNCTIONS IN SCHEMA ${SCHEMA_NAME}
TO ${ADMIN_ROLE};

