GRANT CONNECT ON DATABASE ${DB_NAME} TO ${ADMIN_ROLE};

GRANT USAGE, CREATE ON SCHEMA ${SCHEMA_NAME} TO ${ADMIN_ROLE};

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA ${SCHEMA_NAME}
TO ${ADMIN_ROLE};

GRANT ALL PRIVILEGES
ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME}
TO ${ADMIN_ROLE};

GRANT ALL PRIVILEGES
ON ALL FUNCTIONS IN SCHEMA ${SCHEMA_NAME}
TO ${ADMIN_ROLE};

-- in case tables were created by migration user
ALTER DEFAULT PRIVILEGES FOR ROLE ${ADMIN_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT ON TABLES TO ${RO_ROLE};

ALTER DEFAULT PRIVILEGES FOR ROLE ${ADMIN_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${RW_ROLE};
