GRANT CONNECT ON DATABASE ${DB_NAME} TO ${RW_ROLE};

GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO ${RW_ROLE};

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA ${SCHEMA_NAME}
TO ${RW_ROLE};

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME}
TO ${RW_ROLE};

