GRANT CONNECT ON DATABASE ${DB_NAME} TO ${RO_ROLE};

GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO ${RO_ROLE};

GRANT SELECT
ON ALL TABLES IN SCHEMA ${SCHEMA_NAME}
TO ${RO_ROLE};

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME}
TO ${RO_ROLE};
