GRANT CONNECT ON DATABASE ${DB_NAME} TO ${RO_ROLE};

GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO ${RO_ROLE};

GRANT SELECT
ON ALL TABLES IN SCHEMA ${SCHEMA_NAME}
TO ${RO_ROLE};

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME}
TO ${RO_ROLE};

-- ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME}
-- GRANT SELECT
-- ON TABLES TO ${RO_ROLE};
