-- in case tables were created by admin user

ALTER DEFAULT PRIVILEGES FOR ROLE ${ADMIN_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT ON TABLES TO ${MIGRATION_ROLE};

ALTER DEFAULT PRIVILEGES FOR ROLE ${ADMIN_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT ON TABLES TO ${RO_ROLE};

ALTER DEFAULT PRIVILEGES FOR ROLE ${ADMIN_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${RW_ROLE};

-- in case tables were created by migration user

ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT ON TABLES TO ${ADMIN_ROLE};

ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT ON TABLES TO ${RO_ROLE};

ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${RW_ROLE};

-- in case tables were created by the bootstrap user
ALTER DEFAULT PRIVILEGES
FOR ROLE ${CURRENT_DB_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${ADMIN_ROLE};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${CURRENT_DB_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${MIGRATION_ROLE};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${CURRENT_DB_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ${RW_ROLE};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${CURRENT_DB_USER}
IN SCHEMA ${SCHEMA_NAME}
GRANT SELECT
ON TABLES TO ${RO_ROLE};

